(require 'blackout)

(blackout 'beacon-mode)
(blackout 'company-mode)
(blackout 'editorconfig-mode)
(blackout 'eldoc-mode)
(blackout 'ivy-mode)
(blackout 'linum-relative-mode)
(blackout 'page-break-lines-mode)
(blackout 'projectile-mode)
(blackout 'ryo-modal-mode)
(blackout 'smartparens-mode)
(blackout 'visual-line-mode)
(blackout 'which-key-mode)
(blackout 'yas-minor-mode)
(blackout 'zoom-mode)
;;(blackout 'boon-local-mode)
