* TODO
** TODO Add counsel-org-capture and org-capture-goto-target
   [[file:~/.emacs.d/settings/configs/boon.el][file:~/.emacs.d/settings/configs/boon.el]]
** TODO Add CONFIG for every package if possible!
   [[file:~/.emacs][file:~/.emacs]]
** TODO Add hyperbole!
   [[file:~/.emacs][file:~/.emacs]]
** TODO
   [[https://github.com/tumashu/ivy-posframe][https://github.com/tumashu/ivy-posframe]]
* FIX
** FIX shortcuts and highlights
   [[file:~/.emacs.d/settings/configs/org.el::(setq org-todo-keywords]]
* LINKS
** LINKS DENEME


 (org-capture "http%3a%2f%2fduckduckgo%2ecom&title=DuckDuckGo")
** LINKS
  [[https://github.com/tumashu/ivy-posframehttps:/github.com/tumashu/ivy-posframe][https://github.com/tumashu/ivy-posframehttps:/github.com/tumashu/ivy-posframe]]
 https://github.com/tumashu/ivy-posframehttps:/github.com/tumashu/ivy-posframe
** LINKS
  [[https://github.com/tumashu/ivy-posframehttps:/github.com/tumashu/ivy-posframefunction%20getSelection()%20{%20%20%20%20%5Bnative%20code%5D}][https://github.com/tumashu/ivy-posframehttps:/github.com/tumashu/ivy-posframefunction getSelection() {    {native code}}]]
 https://github.com/tumashu/ivy-posframehttps:/github.com/tumashu/ivy-posframefunction%20getSelection()%20{%20%20%20%20%5Bnative%20code%5D}
** LINKS Remind how genkernel works!
   genkernel is a tool created by Gentoo used to automate the build process of the kernel and initramfs. Some of the general features include:

	 Configuring the kernel sources.
	 Building the compressed kernel bzImage and copying it to /boot.
	 Creating an initramfs and copying it to /boot.
	 Creating symlinks in /boot.
	 Adding custom content to the initramfs such as encryption related files, boot splash images, extra modules, and more.
	 Compressing the initramfs.
	 Configuring the bootloader to boot the newly created kernel and initramfs.
   Source: [[https://wiki.gentoo.org/wiki/Genkernel][genkernel - Gentoo Wiki]]
